name: ExcelToWhitelist
version: '1.0-SNAPSHOT'
main: uf.pcbuilding.exceltowhitelist.ExcelToWhitelist
api-version: '1.21'

permissions:
  exceltowhitelist.command:
    description: "Allows the ability to run /excel-to-whitelist"
    default: op

commands:
  excel-to-whitelist:
    description: "Takes in the provided Excel sheet and adds new users to the whitelist."
    usage: "/excel-to-whitelist"
    permission: exceltowhitelist.command
    permission-message: "You do not have permission to use this command!"